import { describe, it, expect, beforeAll, beforeEach, afterEach } from 'vitest'
import request from 'supertest'
import { app } from '../../server/server'
import fs from 'fs'
import path from 'path'
import sharp from 'sharp'

// Use a dedicated test directory so tests don't pollute the real resources/ dir
const RESOURCES_TEST_DIR = path.join(process.cwd(), 'data', 'resources-test')

// Valid 1x1 test image buffers — generated by sharp so format detection is guaranteed
let PNG_BUFFER: Buffer
let JPEG_BUFFER: Buffer
let WEBP_BUFFER: Buffer

import { RESOURCES_DIR } from '../../server/handlers/resourceHandlers'

beforeAll(async () => {
    PNG_BUFFER = await sharp({ create: { width: 1, height: 1, channels: 3, background: { r: 255, g: 0, b: 0 } } })
        .png()
        .toBuffer()
    JPEG_BUFFER = await sharp({ create: { width: 1, height: 1, channels: 3, background: { r: 0, g: 255, b: 0 } } })
        .jpeg()
        .toBuffer()
    WEBP_BUFFER = await sharp({ create: { width: 1, height: 1, channels: 3, background: { r: 0, g: 0, b: 255 } } })
        .webp()
        .toBuffer()

    if (!fs.existsSync(RESOURCES_TEST_DIR)) {
        fs.mkdirSync(RESOURCES_TEST_DIR, { recursive: true })
    }
    if (!fs.existsSync(RESOURCES_DIR)) {
        fs.mkdirSync(RESOURCES_DIR, { recursive: true })
    }
})

// Snapshot of RESOURCES_DIR files before each test — only new files are removed after
let resourcesDirSnapshot = new Set<string>()

beforeEach(() => {
    if (fs.existsSync(RESOURCES_DIR)) {
        resourcesDirSnapshot = new Set(fs.readdirSync(RESOURCES_DIR))
    } else {
        resourcesDirSnapshot = new Set()
    }
})

const GIT_FILES = new Set(['.gitignore', '.gitkeep'])

afterEach(() => {
    // Remove only files added to RESOURCES_DIR during this test
    if (fs.existsSync(RESOURCES_DIR)) {
        fs.readdirSync(RESOURCES_DIR)
            .filter((f) => !resourcesDirSnapshot.has(f) && !GIT_FILES.has(f))
            .forEach((f) => fs.unlinkSync(path.join(RESOURCES_DIR, f)))
    }
    // Clean RESOURCES_TEST_DIR fully (preserving git files)
    if (fs.existsSync(RESOURCES_TEST_DIR)) {
        fs.readdirSync(RESOURCES_TEST_DIR)
            .filter((f) => !GIT_FILES.has(f))
            .forEach((f) => fs.unlinkSync(path.join(RESOURCES_TEST_DIR, f)))
    }
})

// ---------------------------------------------------------------------------
// Helper: upload a file via supertest
// ---------------------------------------------------------------------------
function uploadFile(buffer: Buffer, filename: string, contentType: string) {
    return request(app).post('/api/resources').attach('file', buffer, { filename, contentType })
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('resourceHandlers', () => {
    describe('GET /api/resources', () => {
        it('should return an empty array when no resources exist', async () => {
            const response = await request(app).get('/api/resources').expect(200)
            expect(Array.isArray(response.body)).toBe(true)
        })

        it('should return resources after upload', async () => {
            await uploadFile(PNG_BUFFER, 'test.png', 'image/png').expect(201)
            const response = await request(app).get('/api/resources').expect(200)
            expect(response.body.length).toBeGreaterThan(0)
        })

        it('should return resources with correct shape', async () => {
            await uploadFile(PNG_BUFFER, 'shape-test.png', 'image/png').expect(201)
            const response = await request(app).get('/api/resources').expect(200)
            const item = response.body[0]
            expect(item).toMatchObject({
                id: expect.any(String),
                mimeType: expect.any(String),
                size: expect.any(Number),
                sizeStr: expect.any(String),
                createdAt: expect.any(String)
            })
        })

        it('should return correct content type header', async () => {
            await request(app).get('/api/resources').expect('Content-Type', /json/)
        })
    })

    describe('POST /api/resources', () => {
        it('should upload a PNG and return 201 with ResourceItem', async () => {
            const response = await uploadFile(PNG_BUFFER, 'photo.png', 'image/png').expect(201)
            expect(response.body).toMatchObject({
                id: expect.stringMatching(/^[0-9a-f-]{36}$/), // UUID v4 format
                mimeType: 'image/png',
                size: expect.any(Number),
                sizeStr: expect.any(String),
                createdAt: expect.any(String)
            })
        })

        it('should upload a JPEG and return 201', async () => {
            const response = await uploadFile(JPEG_BUFFER, 'photo.jpg', 'image/jpeg').expect(201)
            expect(response.body.mimeType).toBe('image/jpeg')
            expect(response.body.id).toMatch(/^[0-9a-f-]{36}$/)
        })

        it('should upload a WebP and return 201', async () => {
            const response = await uploadFile(WEBP_BUFFER, 'photo.webp', 'image/webp').expect(201)
            expect(response.body.mimeType).toBe('image/webp')
        })

        it('should store the file on disk with UUID filename', async () => {
            const response = await uploadFile(PNG_BUFFER, 'stored.png', 'image/png').expect(201)
            const id = response.body.id
            // File should exist in the resources dir as <uuid>.png
            const files = fs.readdirSync(RESOURCES_DIR)
            const found = files.find((f) => f.startsWith(id))
            expect(found).toBeDefined()
            expect(found).toMatch(/^[0-9a-f-]{36}\.(png|jpeg|webp)$/)
        })

        it('should return 400 if no file is attached', async () => {
            const response = await request(app).post('/api/resources').expect(400)
            expect(response.body.error).toBeDefined()
        })

        it('should return 400 for gif upload', async () => {
            // 1-byte buffer with a declared GIF mimetype — multer fileFilter should reject
            const gifBuf = Buffer.from('47494638', 'hex')
            const response = await uploadFile(gifBuf, 'anim.gif', 'image/gif').expect(400)
            expect(response.body.error).toBeDefined()
        })

        it('should set file extension based on sharp-detected format, not declared mimetype', async () => {
            // Upload a PNG buffer but declare it as JPEG — sharp should detect PNG
            // multer fileFilter allows image/png, image/jpeg, both are valid so it passes the filter
            const response = await uploadFile(PNG_BUFFER, 'tricked.jpg', 'image/png').expect(201)
            expect(response.body.mimeType).toBe('image/png')
            const id = response.body.id
            const files = fs.readdirSync(RESOURCES_DIR)
            const found = files.find((f) => f.startsWith(id))
            expect(found).toMatch(/\.png$/)
        })

        it('should return a valid ISO createdAt timestamp', async () => {
            const response = await uploadFile(PNG_BUFFER, 'ts.png', 'image/png').expect(201)
            const date = new Date(response.body.createdAt)
            expect(date.getTime()).not.toBeNaN()
        })
    })

    describe('GET /api/resources/:resourceId/info', () => {
        it('should return metadata for an existing resource', async () => {
            const uploadRes = await uploadFile(PNG_BUFFER, 'info-test.png', 'image/png').expect(201)
            const { id } = uploadRes.body

            const response = await request(app).get(`/api/resources/${id}/info`).expect(200)
            expect(response.body).toMatchObject({
                id,
                mimeType: 'image/png',
                size: expect.any(Number),
                sizeStr: expect.any(String),
                createdAt: expect.any(String)
            })
        })

        it('should return 404 for non-existent resource', async () => {
            const response = await request(app).get('/api/resources/00000000-0000-0000-0000-000000000000/info').expect(404)
            expect(response.body.error).toBeDefined()
        })

        it('should return correct content type header', async () => {
            const uploadRes = await uploadFile(PNG_BUFFER, 'ct-info.png', 'image/png').expect(201)
            await request(app).get(`/api/resources/${uploadRes.body.id}/info`).expect('Content-Type', /json/)
        })
    })

    describe('GET /api/resources/:resourceId', () => {
        it('should return binary PNG with correct Content-Type', async () => {
            const uploadRes = await uploadFile(PNG_BUFFER, 'fetch.png', 'image/png').expect(201)
            const { id } = uploadRes.body

            const response = await request(app).get(`/api/resources/${id}`).expect(200)
            expect(response.headers['content-type']).toMatch(/image\/png/)
            expect(Buffer.isBuffer(response.body) || response.body instanceof Uint8Array).toBe(true)
        })

        it('should return binary JPEG with correct Content-Type', async () => {
            const uploadRes = await uploadFile(JPEG_BUFFER, 'fetch.jpg', 'image/jpeg').expect(201)
            const response = await request(app).get(`/api/resources/${uploadRes.body.id}`).expect(200)
            expect(response.headers['content-type']).toMatch(/image\/jpeg/)
        })

        it('should return 404 for non-existent resource', async () => {
            const response = await request(app).get('/api/resources/00000000-0000-0000-0000-000000000000').expect(404)
            expect(response.body.error).toBeDefined()
        })
    })

    describe('DELETE /api/resources/:resourceId', () => {
        it('should delete resource and return 204', async () => {
            const uploadRes = await uploadFile(PNG_BUFFER, 'del.png', 'image/png').expect(201)
            const { id } = uploadRes.body

            await request(app).delete(`/api/resources/${id}`).expect(204)

            // File should no longer exist on disk
            const files = fs.readdirSync(RESOURCES_DIR)
            const found = files.find((f) => f.startsWith(id))
            expect(found).toBeUndefined()
        })

        it('should return 404 for non-existent resource', async () => {
            const response = await request(app).delete('/api/resources/00000000-0000-0000-0000-000000000000').expect(404)
            expect(response.body.error).toBeDefined()
        })

        it('should not affect other resources', async () => {
            const res1 = await uploadFile(PNG_BUFFER, 'keep.png', 'image/png').expect(201)
            const res2 = await uploadFile(WEBP_BUFFER, 'delete-me.webp', 'image/webp').expect(201)

            await request(app).delete(`/api/resources/${res2.body.id}`).expect(204)

            // res1 should still exist
            const files = fs.readdirSync(RESOURCES_DIR)
            const kept = files.find((f) => f.startsWith(res1.body.id))
            expect(kept).toBeDefined()
        })

        it('should return empty body on successful delete', async () => {
            const uploadRes = await uploadFile(PNG_BUFFER, 'empty-body.png', 'image/png').expect(201)
            const response = await request(app).delete(`/api/resources/${uploadRes.body.id}`).expect(204)
            expect(response.body).toEqual({})
        })
    })
})
